apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for all resources
namespace: ml-platform

resources:
  # 1. Foundation
  - namespace.yaml           # Namespace, quotas, limits
  - secrets.yaml             # Sensitive data (passwords, tokens)
  - configmap.yaml           # Application configuration
  - storageclass.yaml        # Storage definitions

  # 2. Storage
  # PVCs are defined in deployment files (redis, worker)

  # 3. Core Services
  - redis-deployment.yaml    # Redis cache + PVC
  - redis-service.yaml       # Redis service endpoint

  # 4. Application
  - submitter-deployment.yaml # Job submission API
  - worker-deployment.yaml    # GPU workers + PVCs + HPA

  # 5. Scaling & Resilience
  - worker-hpa.yaml          # Auto-scaling rules
  - gpu-operator.yaml        # GPU support + PDB + NetworkPolicy

  # 6. Monitoring
  - servicemonitor.yaml      # Prometheus metrics scraping

  # 7. External Access (Optional - comment out if not needed)
  - ingress.yaml             # HTTPS ingress



commonLabels:
  app.kubernetes.io/name: ml-platform
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: ml-infrastructure



commonAnnotations:
  kubernetes.io/description: "ML GPU Resource Management Platform"
  contact: "ml-platform-team@example.com"
  documentation: "https://github.com/yourorg/ml-platform/blob/main/k8s/README.md"



configMapGenerator:
  - name: ml-platform-env
    literals:
      - ENVIRONMENT=production
      - REGION=us-west-2
      - CLUSTER_NAME=ml-platform-prod
      - LOG_LEVEL=INFO



images:
  # Worker image
  - name: ml-platform-worker
    newName: gcr.io/my-project/ml-platform-worker
    newTag: latest

  # Submitter image
  - name: ml-platform-submitter
    newName: gcr.io/my-project/ml-platform-submitter
    newTag: latest
